Joe/v2
tablelandnetwork/docs pull request #3
Opened 2022-05-12 20:01 UTC by joewagner

WIP updates to match the changes coming with all of the `v2` branches

2022-05-20 17:36 UTC, joewagner commented
Hey @carsonfarmer, Just wanna check that this kind of PR for docs works for you?  I don't have access to gitbook, which is totally fine, so I was planning to make PRs via github.  I have another set of changes to make related to the separation of read and write queries, but wanna make sure I'm doing it right first.
Thanks!

2022-05-25 17:47 UTC, carsonfarmer requested changes
Awesome! This is a great update on the SDK API given all the work you've done on the SDK! I'd made a few suggested changes, and where I couldn't, I've made comments. Minor nit-style updates really.

We'll have to also make some updates to the other sections, including the command line, the RPC endpoints, and more. We'll also eventually have to create updates for the GRANT and REVOKE APIs, and all the work on the Controller contract stuff! I know that is out of scope... just documenting here for posterity.

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +console.log(queryableName); // e.g. mytable_4_1
I can't do a "suggestion" on delete lines for some reason, so here's the suggestion:

```
// `name` will be the prefix, if supplied, with the chain id and
// table id separated by underscores.
console.log(createRes.name)
```

Now that name is much simpler to reason about, I don't think we need to have a separate variable for it here. That makes the example simpler, and highlights that they'll get the name from the response, and they should just use that.

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +console.log(queryableName); // e.g. mytable_4_1
The above obviously implies that we'll need to change all use of queryableName => createRes.name. The alternative is to simply destructure the create response into name and whatever else we want/need in the example for a cleaner demo?

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +// `queryableName` will be the prefix, if you chose one, with the chain id and
Same deal here, keep it simple and just log the name directly.

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
>  const queryableName = createRes.name;
you get the idea

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +console.log(queryableName); // e.g. mytable_4_1
last one

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +1. The chainId of the chain you specified while connecting.
When we make this optional, let's also document that it is optional here. Note also that that means we have to change the structure of the function signature. We can't have an optional as the first argument.

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +2. The column names, datatypes, and constraints that would go inside the parenthesis of a full `CREATE TABLE` statement.
Maybe we should provide an example here?

```
`(
  id int,
  name string,
  value real
)`
```

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +All tables in Tableland are unique, and the way uniqueness is ensured is that each table is named by combining the chainId of the chain the table is minted on, and the id of the ERC-721 token that re
```suggestion
All tables in Tableland are unique, and the way uniqueness is ensured is that each table is named by combining the chainId of the chain the table is minted on, and the id of the ERC-721 token that represents the table. If the prefix is specified it is added to the start of the table name. As such the prefix must follow standard SQL table naming conventions, i.e. the prefix cannot start with a number, and only ASCII characters, numbers, and underscores may be used. For more on the rules of SQL table names see (for example) [Naming Syntax](https://www.postgresql.org/docs/7.0/syntax525.htm)
```

Also no double spaces after a period!

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +Most valid SQL _constraints_ are supported, and the following data types are currently [supported](https://github.com/textileio/go-tableland/blob/main/pkg/parsing/query\_validator.go):
Actually, we should update this to point to the tableland spec docs now: 

```suggestion
Most valid SQL _constraints_ are supported, and the following data types are currently [supported](https://textile.notion.site/Data-Types-4831202597e04823998fe7addc275fea):
```

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
>  * `int2`, `int4`, `int8`, `serial`, `bigserial`
```suggestion
* `int`, `real`, `text`, `blob`, `any`
```

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
>  * `text`, `uri`, `varchar`, `bpchar`
```suggestion

See also the [Data Types docs](https://textile.notion.site/Data-Types-4831202597e04823998fe7addc275fea) for details on representing other common SQL data types using the above core types.
```

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +// `queryableName` will be the prefix, if you chose one, with the chain id and
same again, wow we use this example a lot!

2022-05-25 17:47 UTC, carsonfarmer commented on building/javascript-sdk.md
> +Creating a table generates a unique table identifier (table id). The table id is unique within the specified chain and can be used to reference the table for queries and updates after it has been cre
```suggestion
Creating a table generates a unique table identifier (table id). The table id is unique within the specified chain and can be used to reference the table for queries and updates after it has been created.  This table id is the tokenId from the Tableland Registry Smart Contract which means you can view your table on any blockchain scanner associated with the chain your table was minted on. Here is an example of a Tableland rinkeby table viewed on [Opensea](https://testnets.opensea.io/assets/0x30867ad98a520287ccc28cde70fcf63e3cdb9c3c/723)
```

2022-05-26 00:02 UTC, carsonfarmer approved these changes
Sweet!

2022-05-26 02:28 UTC, merged